# Generated by Django 3.2.5 on 2022-09-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Complete', 'Completado'), ('New', 'Nuevo'), ('Accepted', 'Aceptado'), ('Cancelled', 'Cancelado')], default='New', max_length=50),
        ),
    ]
